#!/usr/bin/env node
// Make dark-mode versions of house-style sources.
//
//   node skills/lib/make-dark.mjs <src dir> [...more]      → writes <src dir>-dark/ beside each
//   node skills/lib/make-dark.mjs --kits                   → (re)builds design-languages/kits/*.dark.css
//
// The house style is strictly greyscale, so dark mode is a deterministic remap:
// every grey maps to its dark-theme partner (paper → near-black, ink → near-white,
// mist outlines → dark-grey outlines…), so emphasis is preserved. The answer stays
// the highest-contrast element on the page. Rules:
//   • only greyscale hex literals are touched (#c41-style CSS ids are left alone)
//   • radial gradients (spheres) keep their shading direction: highlights stay lighter
//   • kit links are swapped to the *.dark.css kits; local .css/.js files are converted too
// Sources are never modified; dark copies are written next to them.

import { readFileSync, writeFileSync, readdirSync, mkdirSync, statSync, copyFileSync } from "node:fs";
import { join, dirname, resolve, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

// Light grey value → dark grey value. Anchors are the house-style tokens (see house-style.md §2b).
const ANCHORS = [
  [0, 250], [13, 242],   // ink        #0D0D0D → #F2F2F2
  [51, 217],             // graphite   #333333 → #D9D9D9
  [107, 163],            // stone      #6B6B6B → #A3A3A3
  [166, 110],            // ash        #A6A6A6 → #6E6E6E
  [214, 58],             // mist       #D6D6D6 → #3A3A3A
  [237, 34],             // fog        #EDEDED → #222222
  [246, 23],             // snow       #F6F6F6 → #171717
  [255, 13],             // paper      #FFFFFF → #0D0D0D
];
export function mapGrey(v) {
  for (let i = 1; i < ANCHORS.length; i++) {
    const [x0, y0] = ANCHORS[i - 1], [x1, y1] = ANCHORS[i];
    if (v <= x1) return Math.round(y0 + ((v - x0) / (x1 - x0)) * (y1 - y0));
  }
  return ANCHORS.at(-1)[1];
}

const HEX = /#([0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{4}|[0-9a-fA-F]{3})\b/g;
const parse = (h) => {
  let s = h.slice(1);
  if (s.length <= 4) s = [...s].map((c) => c + c).join("");
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(s.slice(i, i + 2), 16));
  return { r, g, b, a: s.length === 8 ? s.slice(6) : "" };
};
const isGrey = ({ r, g, b }) => r === g && g === b;
const hex = (v, a = "") => "#" + Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0").toUpperCase().repeat(3) + a;

function mapPlain(text) {
  return text.replace(HEX, (m) => { const c = parse(m); return isGrey(c) ? hex(mapGrey(c.r), c.a) : m; });
}

// Radial gradients are lit forms (spheres): move the mean tone, keep the highlight lighter.
function mapRadial(body) {
  const stops = [...body.matchAll(HEX)].map((m) => parse(m[0])).filter(isGrey);
  if (!stops.length) return body;
  const mean = stops.reduce((s, c) => s + c.r, 0) / stops.length;
  const shift = mapGrey(mean) - mean;
  return body.replace(HEX, (m) => { const c = parse(m); return isGrey(c) ? hex(c.r + shift, c.a) : m; });
}

export function darken(text) {
  let out = "", i = 0;
  const re = /radial-gradient\(/g;
  let m;
  while ((m = re.exec(text))) {
    // find the matching ")"
    let depth = 1, j = m.index + m[0].length;
    while (j < text.length && depth) { if (text[j] === "(") depth++; else if (text[j] === ")") depth--; j++; }
    out += mapPlain(text.slice(i, m.index)) + "radial-gradient(" + mapRadial(text.slice(m.index + m[0].length, j - 1)) + ")";
    i = j; re.lastIndex = j;
  }
  return out + mapPlain(text.slice(i));
}

function convertHtml(text) {
  return darken(text)
    .replace(/kits\/mono\.css/g, "kits/mono.dark.css")
    .replace(/kits\/folk-motion\.css/g, "kits/folk-motion.dark.css");
}

const DARK_KIT_NOTE = (name) => `/* GENERATED by skills/lib/make-dark.mjs from ${name}. Do not edit; edit the light kit and re-run with --kits. */\n`;
function buildKits() {
  const kits = join(ROOT, "design-languages/kits");
  const mono = readFileSync(join(kits, "mono.css"), "utf8");
  writeFileSync(join(kits, "mono.dark.css"), DARK_KIT_NOTE("mono.css") + darken(mono) + `
/* Dark-mode specifics ------------------------------------------------------ */
:root { color-scheme: dark; }
/* SVG shapes and text with no fill default to black; make that default ink. */
.canvas svg:not(.lucide):not([fill]) { fill: var(--ink); }
`);
  const folk = readFileSync(join(kits, "folk-motion.css"), "utf8");
  writeFileSync(join(kits, "folk-motion.dark.css"), DARK_KIT_NOTE("folk-motion.css") + darken(folk) + `
/* Dark-mode grain: light speckle that screens onto the dark stage. */
.grain { mix-blend-mode: screen; filter: invert(1); opacity: .22; }
`);
  console.log("✓ design-languages/kits/mono.dark.css\n✓ design-languages/kits/folk-motion.dark.css");
}

function convertDir(dir) {
  const src = resolve(dir), dest = src.replace(/\/?$/, "") + "-dark";
  mkdirSync(dest, { recursive: true });
  for (const f of readdirSync(src)) {
    const p = join(src, f);
    if (statSync(p).isDirectory()) continue;
    const ext = extname(f);
    if (ext === ".html") writeFileSync(join(dest, f), convertHtml(readFileSync(p, "utf8")));
    else if (ext === ".css" || ext === ".js" || ext === ".svg") writeFileSync(join(dest, f), darken(readFileSync(p, "utf8")));
    else copyFileSync(p, join(dest, f));
  }
  console.log(`✓ ${dest}`);
}

const args = process.argv.slice(2);
if (!args.length) { console.error("usage: make-dark.mjs --kits | <src dir> […]"); process.exit(1); }
if (args.includes("--kits")) buildKits();
for (const a of args.filter((x) => x !== "--kits")) convertDir(a);
